// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasks_usingEF.Database;

#nullable disable

namespace Tasks_usingEF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tasks_usingEF.Models.Division", b =>
                {
                    b.Property<long>("DIVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DIVID"));

                    b.Property<string>("DivName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DIVID");

                    b.ToTable("divisions");
                });

            modelBuilder.Entity("Tasks_usingEF.Models.Employee", b =>
                {
                    b.Property<long>("EID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EID"));

                    b.Property<long>("DIVID")
                        .HasColumnType("bigint");

                    b.Property<string>("EMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ename")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("EID");

                    b.HasIndex("DIVID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Tasks_usingEF.Models.EmployeeProjects", b =>
                {
                    b.Property<long>("EPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EPID"));

                    b.Property<long>("EID")
                        .HasColumnType("bigint");

                    b.Property<long>("PID")
                        .HasColumnType("bigint");

                    b.HasKey("EPID");

                    b.HasIndex("EID");

                    b.HasIndex("PID");

                    b.ToTable("EmployeeProjects");
                });

            modelBuilder.Entity("Tasks_usingEF.Models.Projects", b =>
                {
                    b.Property<long>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PID"));

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectTeamSize")
                        .HasColumnType("int");

                    b.Property<decimal>("Projectbudjet")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Tasks_usingEF.Models.Employee", b =>
                {
                    b.HasOne("Tasks_usingEF.Models.Division", "division")
                        .WithMany()
                        .HasForeignKey("DIVID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("division");
                });

            modelBuilder.Entity("Tasks_usingEF.Models.EmployeeProjects", b =>
                {
                    b.HasOne("Tasks_usingEF.Models.Employee", "employees")
                        .WithMany()
                        .HasForeignKey("EID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tasks_usingEF.Models.Projects", "projects")
                        .WithMany()
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("employees");

                    b.Navigation("projects");
                });
#pragma warning restore 612, 618
        }
    }
}
